management:
  endpoints:
    web:
      exposure:
        include: "*"
    prometheus:
      enabled: true
server:
  tomcat:
    mbeanregistry:
      enabled: true
logging:
  config: classpath:logback-spring.xml
spring:
  output:
    ansi:
      enabled: always